"""pool contact group name

Revision ID: 21acf5886776
Revises: 6099818a2f60
Create Date: 2026-10-02 02:56:23.191410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21acf5886776'
down_revision = '6099818a2f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_pool_contact_group_name'), ['group_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pool_contact_group_name'))
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
