"""widen campaign.sender_id and campaign_schedule.sender_id to 60

Revision ID: 508cc3d00061
Revises: 67ace10010aa
Create Date: 2026-10-03 14:25:09.746361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508cc3d00061'
down_revision = '67ace10010aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=60),
               existing_nullable=False)

    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
