"""plan tier fields

Revision ID: 53e455d06699
Revises: c0083793461a
Create Date: 2026-10-01 20:43:00.280619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e455d06699'
down_revision = 'c0083793461a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tier_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_plan_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_sort_order'), ['sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_sort_order'))
        batch_op.drop_index(batch_op.f('ix_plan_is_active'))
        batch_op.drop_column('is_featured')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('tier_max')
        batch_op.drop_column('tier_min')

    # ### end Alembic commands ###
