"""initial schema

Revision ID: 5e5fea16ea4e
Revises: 
Create Date: 2026-10-07 07:19:56.035649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5fea16ea4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_district_name')
    )
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_district_region'), ['region'], unique=False)

    op.create_table('opt_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opt_out', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opt_out_phone'), ['phone'], unique=True)

    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('tier_min', sa.Integer(), nullable=True),
    sa.Column('tier_max', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('max_contacts', sa.Integer(), nullable=True),
    sa.Column('max_per_minute', sa.Integer(), nullable=True),
    sa.Column('max_per_day', sa.Integer(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_sort_order'), ['sort_order'], unique=False)

    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('brand_name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name='fk_organization_district'),
    sa.ForeignKeyConstraint(['parent_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_organization_status'), ['status'], unique=False)

    op.create_table('chat_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('associate_org_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['associate_org_id'], ['organization.id'], name='fk_chat_channel_associate_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'associate_org_id', name='uq_chat_channel_kind_org')
    )
    with op.batch_alter_table('chat_channel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_channel_associate_org_id'), ['associate_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_channel_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_channel_last_message_at'), ['last_message_at'], unique=False)

    op.create_table('contact_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_org_group_name')
    )
    with op.batch_alter_table('contact_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_group_org_id'), ['org_id'], unique=False)

    op.create_table('message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_template_org_id'), ['org_id'], unique=False)

    op.create_table('pool_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('group_name', sa.String(length=80), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('source_org_id', sa.Integer(), nullable=False),
    sa.Column('source_contact_id', sa.Integer(), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name='fk_pool_contact_district'),
    sa.ForeignKeyConstraint(['source_org_id'], ['organization.id'], name='fk_pool_contact_source_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_org_id', 'phone', name='uq_pool_source_phone')
    )
    with op.batch_alter_table('pool_contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pool_contact_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pool_contact_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pool_contact_opted_out'), ['opted_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_pool_contact_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_pool_contact_source_org_id'), ['source_org_id'], unique=False)

    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('credits_granted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_status'), ['status'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_org_id'), ['org_id'], unique=False)

    op.create_table('campaign_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.String(length=60), nullable=False),
    sa.Column('scheduled_times', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pause_reason', sa.String(length=255), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('runs_completed', sa.Integer(), nullable=True),
    sa.Column('runs_skipped', sa.Integer(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_failed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_schedule_creator'),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name='fk_schedule_district'),
    sa.ForeignKeyConstraint(['group_id'], ['contact_group.id'], name='fk_schedule_group'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name='fk_schedule_org'),
    sa.ForeignKeyConstraint(['template_id'], ['message_template.id'], name='fk_schedule_template'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_schedule_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_schedule_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_schedule_status'), ['status'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='fk_chat_message_author'),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channel.id'], name='fk_chat_message_channel'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_author_id'), ['author_id'], unique=False)
        batch_op.create_index('ix_chat_message_channel_created', ['channel_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_created_at'), ['created_at'], unique=False)

    op.create_table('chat_read_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channel.id'], name='fk_chat_read_channel'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_chat_read_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_chat_read_user_channel')
    )
    with op.batch_alter_table('chat_read_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_read_state_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_read_state_user_id'), ['user_id'], unique=False)

    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('group', sa.String(length=80), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name='fk_contact_district'),
    sa.ForeignKeyConstraint(['group_id'], ['contact_group.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'phone', name='uq_org_phone')
    )
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_phone'), ['phone'], unique=False)

    op.create_table('contact_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('on_duplicate', sa.String(length=10), nullable=True),
    sa.Column('default_group', sa.String(length=80), nullable=True),
    sa.Column('default_district_id', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('added', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('skipped_duplicate', sa.Integer(), nullable=True),
    sa.Column('skipped_in_file', sa.Integer(), nullable=True),
    sa.Column('skipped_opt_out', sa.Integer(), nullable=True),
    sa.Column('invalid', sa.Integer(), nullable=True),
    sa.Column('groups_created', sa.Integer(), nullable=True),
    sa.Column('districts_matched', sa.Integer(), nullable=True),
    sa.Column('districts_unmatched', sa.Integer(), nullable=True),
    sa.Column('cap_hit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_district_id'], ['district.id'], name='fk_contact_import_district'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name='fk_contact_import_org'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_contact_import_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_import', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_import_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_import_org_id'), ['org_id'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('payment_reference', sa.String(length=120), nullable=True),
    sa.Column('marked_paid_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['marked_paid_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uq_invoice_number')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_issued_at'), ['issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)

    op.create_table('notification_dismissal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_notification_dismissal_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_notification_dismissal_user_key')
    )
    with op.batch_alter_table('notification_dismissal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_dismissal_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_dismissal_user_id'), ['user_id'], unique=False)

    op.create_table('pool_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('agreement_version', sa.String(length=20), nullable=True),
    sa.Column('agreement_text', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], name='fk_pool_permission_granted_by'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name='fk_pool_permission_org'),
    sa.ForeignKeyConstraint(['revoked_by'], ['user.id'], name='fk_pool_permission_revoked_by'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pool_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pool_permission_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_pool_permission_org_status', ['org_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pool_permission_status'), ['status'], unique=False)

    op.create_table('signup_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('desired_slug', sa.String(length=60), nullable=False),
    sa.Column('brand_name', sa.String(length=60), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=150), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('expected_volume', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('created_org_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_org_id'], ['organization.id'], name='fk_signup_org'),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], name='fk_signup_user'),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name='fk_signup_district'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name='fk_signup_plan'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name='fk_signup_reviewer'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signup_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signup_request_contact_email'), ['contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_request_desired_slug'), ['desired_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_request_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_request_status'), ['status'], unique=False)
        batch_op.create_index('ix_signup_status_created', ['status', 'created_at'], unique=False)

    op.create_table('wallet_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('source_org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['source_org_id'], ['organization.id'], name='fk_wallet_source_org'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_transaction', schema=None) as batch_op:
        batch_op.create_index('ix_wallet_org_created', ['org_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transaction_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transaction_source_org_id'), ['source_org_id'], unique=False)

    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.String(length=60), nullable=False),
    sa.Column('group_filter', sa.String(length=80), nullable=True),
    sa.Column('district_filter', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('credits_debited', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['campaign_schedule.id'], name='fk_campaign_schedule'),
    sa.ForeignKeyConstraint(['template_id'], ['message_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_status'), ['status'], unique=False)

    op.create_table('contact_import_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('row_num', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('raw_phone', sa.String(length=60), nullable=True),
    sa.Column('canonical', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('group_name', sa.String(length=80), nullable=True),
    sa.Column('district_name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['contact_import.id'], name='fk_contact_import_issue_import'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_import_issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_import_issue_import_id'), ['import_id'], unique=False)
        batch_op.create_index('ix_contact_import_issue_import_status', ['import_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_import_issue_status'), ['status'], unique=False)

    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('api_response', sa.Text(), nullable=True),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('provider_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('delivery_status_raw', sa.String(length=40), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_log_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_log_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_log_provider_ref'), ['provider_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_log_status'), ['status'], unique=False)

    op.create_table('send_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_after', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('send_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_send_queue_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_send_queue_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_send_queue_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_send_queue_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_send_queue_status'))
        batch_op.drop_index(batch_op.f('ix_send_queue_run_after'))
        batch_op.drop_index(batch_op.f('ix_send_queue_org_id'))
        batch_op.drop_index(batch_op.f('ix_send_queue_campaign_id'))

    op.drop_table('send_queue')
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_log_status'))
        batch_op.drop_index(batch_op.f('ix_message_log_provider_ref'))
        batch_op.drop_index(batch_op.f('ix_message_log_org_id'))
        batch_op.drop_index(batch_op.f('ix_message_log_campaign_id'))

    op.drop_table('message_log')
    with op.batch_alter_table('contact_import_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_import_issue_status'))
        batch_op.drop_index('ix_contact_import_issue_import_status')
        batch_op.drop_index(batch_op.f('ix_contact_import_issue_import_id'))

    op.drop_table('contact_import_issue')
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_org_id'))

    op.drop_table('campaign')
    with op.batch_alter_table('wallet_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_transaction_source_org_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transaction_org_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transaction_created_at'))
        batch_op.drop_index('ix_wallet_org_created')

    op.drop_table('wallet_transaction')
    with op.batch_alter_table('signup_request', schema=None) as batch_op:
        batch_op.drop_index('ix_signup_status_created')
        batch_op.drop_index(batch_op.f('ix_signup_request_status'))
        batch_op.drop_index(batch_op.f('ix_signup_request_district_id'))
        batch_op.drop_index(batch_op.f('ix_signup_request_desired_slug'))
        batch_op.drop_index(batch_op.f('ix_signup_request_created_at'))
        batch_op.drop_index(batch_op.f('ix_signup_request_contact_email'))

    op.drop_table('signup_request')
    with op.batch_alter_table('pool_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pool_permission_status'))
        batch_op.drop_index('ix_pool_permission_org_status')
        batch_op.drop_index(batch_op.f('ix_pool_permission_org_id'))

    op.drop_table('pool_permission')
    with op.batch_alter_table('notification_dismissal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_dismissal_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_dismissal_key'))

    op.drop_table('notification_dismissal')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_org_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoice_issued_at'))

    op.drop_table('invoice')
    with op.batch_alter_table('contact_import', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_import_org_id'))
        batch_op.drop_index(batch_op.f('ix_contact_import_created_at'))

    op.drop_table('contact_import')
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_phone'))
        batch_op.drop_index(batch_op.f('ix_contact_org_id'))
        batch_op.drop_index(batch_op.f('ix_contact_group_id'))
        batch_op.drop_index(batch_op.f('ix_contact_group'))
        batch_op.drop_index(batch_op.f('ix_contact_district_id'))

    op.drop_table('contact')
    with op.batch_alter_table('chat_read_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_read_state_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_read_state_channel_id'))

    op.drop_table('chat_read_state')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_message_channel_id'))
        batch_op.drop_index('ix_chat_message_channel_created')
        batch_op.drop_index(batch_op.f('ix_chat_message_author_id'))

    op.drop_table('chat_message')
    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_schedule_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_schedule_org_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_schedule_next_run_at'))

    op.drop_table('campaign_schedule')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_org_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_status'))
        batch_op.drop_index(batch_op.f('ix_subscription_org_id'))

    op.drop_table('subscription')
    with op.batch_alter_table('pool_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pool_contact_source_org_id'))
        batch_op.drop_index(batch_op.f('ix_pool_contact_phone'))
        batch_op.drop_index(batch_op.f('ix_pool_contact_opted_out'))
        batch_op.drop_index(batch_op.f('ix_pool_contact_group_name'))
        batch_op.drop_index(batch_op.f('ix_pool_contact_district_id'))

    op.drop_table('pool_contact')
    with op.batch_alter_table('message_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_template_org_id'))

    op.drop_table('message_template')
    with op.batch_alter_table('contact_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_group_org_id'))

    op.drop_table('contact_group')
    with op.batch_alter_table('chat_channel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_channel_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_chat_channel_kind'))
        batch_op.drop_index(batch_op.f('ix_chat_channel_associate_org_id'))

    op.drop_table('chat_channel')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_status'))
        batch_op.drop_index(batch_op.f('ix_organization_slug'))
        batch_op.drop_index(batch_op.f('ix_organization_is_system'))
        batch_op.drop_index(batch_op.f('ix_organization_district_id'))

    op.drop_table('organization')
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_sort_order'))
        batch_op.drop_index(batch_op.f('ix_plan_is_active'))

    op.drop_table('plan')
    with op.batch_alter_table('opt_out', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opt_out_phone'))

    op.drop_table('opt_out')
    with op.batch_alter_table('district', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_district_region'))
        batch_op.drop_index(batch_op.f('ix_district_name'))

    op.drop_table('district')
    # ### end Alembic commands ###
