"""contact import reports

Revision ID: 6099818a2f60
Revises: b27d78a75e72
Create Date: 2026-10-02 02:32:06.431508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6099818a2f60'
down_revision = 'b27d78a75e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('on_duplicate', sa.String(length=10), nullable=True),
    sa.Column('default_group', sa.String(length=80), nullable=True),
    sa.Column('default_district_id', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('added', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('skipped_duplicate', sa.Integer(), nullable=True),
    sa.Column('skipped_in_file', sa.Integer(), nullable=True),
    sa.Column('skipped_opt_out', sa.Integer(), nullable=True),
    sa.Column('invalid', sa.Integer(), nullable=True),
    sa.Column('groups_created', sa.Integer(), nullable=True),
    sa.Column('districts_matched', sa.Integer(), nullable=True),
    sa.Column('districts_unmatched', sa.Integer(), nullable=True),
    sa.Column('cap_hit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_district_id'], ['district.id'], name='fk_contact_import_district'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name='fk_contact_import_org'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_contact_import_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_import', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_import_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_import_org_id'), ['org_id'], unique=False)

    op.create_table('contact_import_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('row_num', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('raw_phone', sa.String(length=60), nullable=True),
    sa.Column('canonical', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('group_name', sa.String(length=80), nullable=True),
    sa.Column('district_name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['contact_import.id'], name='fk_contact_import_issue_import'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_import_issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_import_issue_import_id'), ['import_id'], unique=False)
        batch_op.create_index('ix_contact_import_issue_import_status', ['import_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_import_issue_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_import_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_import_issue_status'))
        batch_op.drop_index('ix_contact_import_issue_import_status')
        batch_op.drop_index(batch_op.f('ix_contact_import_issue_import_id'))

    op.drop_table('contact_import_issue')
    with op.batch_alter_table('contact_import', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_import_org_id'))
        batch_op.drop_index(batch_op.f('ix_contact_import_created_at'))

    op.drop_table('contact_import')
    # ### end Alembic commands ###
