"""campaign schedules

Revision ID: 67ace10010aa
Revises: 21acf5886776
Create Date: 2026-10-02 16:23:37.741796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ace10010aa'
down_revision = '21acf5886776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.String(length=11), nullable=False),
    sa.Column('days_of_week', sa.String(length=30), nullable=False),
    sa.Column('times_of_day', sa.Text(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pause_reason', sa.String(length=255), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('runs_completed', sa.Integer(), nullable=True),
    sa.Column('runs_skipped', sa.Integer(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_failed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_schedule_creator'),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name='fk_schedule_district'),
    sa.ForeignKeyConstraint(['group_id'], ['contact_group.id'], name='fk_schedule_group'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name='fk_schedule_org'),
    sa.ForeignKeyConstraint(['template_id'], ['message_template.id'], name='fk_schedule_template'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_schedule_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_schedule_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_schedule_status'), ['status'], unique=False)

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_campaign_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_foreign_key('fk_campaign_schedule', 'campaign_schedule', ['schedule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaign_schedule', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_campaign_schedule_id'))
        batch_op.drop_column('schedule_id')

    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_schedule_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_schedule_org_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_schedule_next_run_at'))

    op.drop_table('campaign_schedule')
    # ### end Alembic commands ###
