"""signup requests

Revision ID: b27d78a75e72
Revises: 53e455d06699
Create Date: 2026-10-01 22:16:10.997519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27d78a75e72'
down_revision = '53e455d06699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('desired_slug', sa.String(length=60), nullable=False),
    sa.Column('brand_name', sa.String(length=60), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=150), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('expected_volume', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('created_org_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_org_id'], ['organization.id'], name='fk_signup_org'),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], name='fk_signup_user'),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name='fk_signup_district'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name='fk_signup_plan'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name='fk_signup_reviewer'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signup_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signup_request_contact_email'), ['contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_request_desired_slug'), ['desired_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_request_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_request_status'), ['status'], unique=False)
        batch_op.create_index('ix_signup_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_request', schema=None) as batch_op:
        batch_op.drop_index('ix_signup_status_created')
        batch_op.drop_index(batch_op.f('ix_signup_request_status'))
        batch_op.drop_index(batch_op.f('ix_signup_request_district_id'))
        batch_op.drop_index(batch_op.f('ix_signup_request_desired_slug'))
        batch_op.drop_index(batch_op.f('ix_signup_request_created_at'))
        batch_op.drop_index(batch_op.f('ix_signup_request_contact_email'))

    op.drop_table('signup_request')
    # ### end Alembic commands ###
