"""empty message

Revision ID: ef35273d923c
Revises: 508cc3d00061
Create Date: 2026-10-03 22:54:04.741884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef35273d923c'
down_revision = '508cc3d00061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_times', sa.Text(), nullable=False))
        batch_op.drop_column('days_of_week')
        batch_op.drop_column('times_of_day')
        batch_op.drop_column('ends_on')
        batch_op.drop_column('starts_on')

    # ### end Alembic commands ###


def downgrade():
    # The three-step pattern: add nullable, backfill, then alter.
    # A direct NOT NULL add fails on tables that already have rows,
    # because Postgres cannot invent a value for the existing rows.
    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starts_on', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('ends_on', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('times_of_day', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('days_of_week', sa.VARCHAR(length=30), nullable=True))

    # Backfill with sensible defaults so the NOT NULL constraint can be applied.
    # `starts_on` is required on the old schema, so every existing row needs a
    # value — we use today. `times_of_day` and `days_of_week` are also required
    # on the old schema; defaults keep the rows valid.
    op.execute("""
        UPDATE campaign_schedule
        SET starts_on = CURRENT_DATE,
            times_of_day = '["09:00"]',
            days_of_week = 'mon'
        WHERE starts_on IS NULL
    """)

    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.alter_column('starts_on', nullable=False)
        batch_op.alter_column('times_of_day', nullable=False)
        batch_op.alter_column('days_of_week', nullable=False)
        batch_op.drop_column('scheduled_times')