"""empty message

Revision ID: ef35273d923c
Revises: 508cc3d00061
Create Date: 2026-10-03 22:54:04.741884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef35273d923c'
down_revision = '508cc3d00061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_times', sa.Text(), nullable=False))
        batch_op.drop_column('days_of_week')
        batch_op.drop_column('times_of_day')
        batch_op.drop_column('ends_on')
        batch_op.drop_column('starts_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starts_on', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ends_on', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('times_of_day', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('days_of_week', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('scheduled_times')

    # ### end Alembic commands ###
